package c.b.a.a;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class d
{
  static Map<Integer, List<String>> a()
  {
    HashMap localHashMap = new HashMap(286);
    ArrayList localArrayList1 = new ArrayList(25);
    localArrayList1.add("US");
    localArrayList1.add("AG");
    localArrayList1.add("AI");
    localArrayList1.add("AS");
    localArrayList1.add("BB");
    localArrayList1.add("BM");
    localArrayList1.add("BS");
    localArrayList1.add("CA");
    localArrayList1.add("DM");
    localArrayList1.add("DO");
    localArrayList1.add("GD");
    localArrayList1.add("GU");
    localArrayList1.add("JM");
    localArrayList1.add("KN");
    localArrayList1.add("KY");
    localArrayList1.add("LC");
    localArrayList1.add("MP");
    localArrayList1.add("MS");
    localArrayList1.add("PR");
    localArrayList1.add("SX");
    localArrayList1.add("TC");
    localArrayList1.add("TT");
    localArrayList1.add("VC");
    localArrayList1.add("VG");
    localArrayList1.add("VI");
    localHashMap.put(Integer.valueOf(1), localArrayList1);
    ArrayList localArrayList3 = new ArrayList(2);
    localArrayList3.add("RU");
    localArrayList3.add("KZ");
    localHashMap.put(Integer.valueOf(7), localArrayList3);
    ArrayList localArrayList4 = new ArrayList(1);
    localArrayList4.add("EG");
    localHashMap.put(Integer.valueOf(20), localArrayList4);
    ArrayList localArrayList5 = new ArrayList(1);
    localArrayList5.add("ZA");
    localHashMap.put(Integer.valueOf(27), localArrayList5);
    ArrayList localArrayList6 = new ArrayList(1);
    localArrayList6.add("GR");
    localHashMap.put(Integer.valueOf(30), localArrayList6);
    ArrayList localArrayList7 = new ArrayList(1);
    localArrayList7.add("NL");
    localHashMap.put(Integer.valueOf(31), localArrayList7);
    ArrayList localArrayList8 = new ArrayList(1);
    localArrayList8.add("BE");
    localHashMap.put(Integer.valueOf(32), localArrayList8);
    ArrayList localArrayList9 = new ArrayList(1);
    localArrayList9.add("FR");
    localHashMap.put(Integer.valueOf(33), localArrayList9);
    ArrayList localArrayList10 = new ArrayList(1);
    localArrayList10.add("ES");
    localHashMap.put(Integer.valueOf(34), localArrayList10);
    ArrayList localArrayList11 = new ArrayList(1);
    localArrayList11.add("HU");
    localHashMap.put(Integer.valueOf(36), localArrayList11);
    ArrayList localArrayList12 = new ArrayList(2);
    localArrayList12.add("IT");
    localArrayList12.add("VA");
    localHashMap.put(Integer.valueOf(39), localArrayList12);
    ArrayList localArrayList13 = new ArrayList(1);
    localArrayList13.add("RO");
    localHashMap.put(Integer.valueOf(40), localArrayList13);
    ArrayList localArrayList14 = new ArrayList(1);
    localArrayList14.add("CH");
    localHashMap.put(Integer.valueOf(41), localArrayList14);
    ArrayList localArrayList15 = new ArrayList(1);
    localArrayList15.add("AT");
    localHashMap.put(Integer.valueOf(43), localArrayList15);
    ArrayList localArrayList16 = new ArrayList(4);
    localArrayList16.add("GB");
    localArrayList16.add("GG");
    localArrayList16.add("IM");
    localArrayList16.add("JE");
    localHashMap.put(Integer.valueOf(44), localArrayList16);
    ArrayList localArrayList17 = new ArrayList(1);
    localArrayList17.add("DK");
    localHashMap.put(Integer.valueOf(45), localArrayList17);
    ArrayList localArrayList18 = new ArrayList(1);
    localArrayList18.add("SE");
    localHashMap.put(Integer.valueOf(46), localArrayList18);
    ArrayList localArrayList19 = new ArrayList(2);
    localArrayList19.add("NO");
    localArrayList19.add("SJ");
    localHashMap.put(Integer.valueOf(47), localArrayList19);
    ArrayList localArrayList20 = new ArrayList(1);
    localArrayList20.add("PL");
    localHashMap.put(Integer.valueOf(48), localArrayList20);
    ArrayList localArrayList21 = new ArrayList(1);
    localArrayList21.add("DE");
    localHashMap.put(Integer.valueOf(49), localArrayList21);
    ArrayList localArrayList22 = new ArrayList(1);
    localArrayList22.add("PE");
    localHashMap.put(Integer.valueOf(51), localArrayList22);
    ArrayList localArrayList23 = new ArrayList(1);
    localArrayList23.add("MX");
    localHashMap.put(Integer.valueOf(52), localArrayList23);
    ArrayList localArrayList24 = new ArrayList(1);
    localArrayList24.add("CU");
    localHashMap.put(Integer.valueOf(53), localArrayList24);
    ArrayList localArrayList25 = new ArrayList(1);
    localArrayList25.add("AR");
    localHashMap.put(Integer.valueOf(54), localArrayList25);
    ArrayList localArrayList26 = new ArrayList(1);
    localArrayList26.add("BR");
    localHashMap.put(Integer.valueOf(55), localArrayList26);
    ArrayList localArrayList27 = new ArrayList(1);
    localArrayList27.add("CL");
    localHashMap.put(Integer.valueOf(56), localArrayList27);
    ArrayList localArrayList28 = new ArrayList(1);
    localArrayList28.add("CO");
    localHashMap.put(Integer.valueOf(57), localArrayList28);
    ArrayList localArrayList29 = new ArrayList(1);
    localArrayList29.add("VE");
    localHashMap.put(Integer.valueOf(58), localArrayList29);
    ArrayList localArrayList30 = new ArrayList(1);
    localArrayList30.add("MY");
    localHashMap.put(Integer.valueOf(60), localArrayList30);
    ArrayList localArrayList31 = new ArrayList(3);
    localArrayList31.add("AU");
    localArrayList31.add("CC");
    localArrayList31.add("CX");
    localHashMap.put(Integer.valueOf(61), localArrayList31);
    ArrayList localArrayList32 = new ArrayList(1);
    localArrayList32.add("ID");
    localHashMap.put(Integer.valueOf(62), localArrayList32);
    ArrayList localArrayList33 = new ArrayList(1);
    localArrayList33.add("PH");
    localHashMap.put(Integer.valueOf(63), localArrayList33);
    ArrayList localArrayList34 = new ArrayList(1);
    localArrayList34.add("NZ");
    localHashMap.put(Integer.valueOf(64), localArrayList34);
    ArrayList localArrayList35 = new ArrayList(1);
    localArrayList35.add("SG");
    localHashMap.put(Integer.valueOf(65), localArrayList35);
    ArrayList localArrayList36 = new ArrayList(1);
    localArrayList36.add("TH");
    localHashMap.put(Integer.valueOf(66), localArrayList36);
    ArrayList localArrayList37 = new ArrayList(1);
    localArrayList37.add("JP");
    localHashMap.put(Integer.valueOf(81), localArrayList37);
    ArrayList localArrayList38 = new ArrayList(1);
    localArrayList38.add("KR");
    localHashMap.put(Integer.valueOf(82), localArrayList38);
    ArrayList localArrayList39 = new ArrayList(1);
    localArrayList39.add("VN");
    localHashMap.put(Integer.valueOf(84), localArrayList39);
    ArrayList localArrayList40 = new ArrayList(1);
    localArrayList40.add("CN");
    localHashMap.put(Integer.valueOf(86), localArrayList40);
    ArrayList localArrayList41 = new ArrayList(1);
    localArrayList41.add("TR");
    localHashMap.put(Integer.valueOf(90), localArrayList41);
    ArrayList localArrayList42 = new ArrayList(1);
    localArrayList42.add("IN");
    localHashMap.put(Integer.valueOf(91), localArrayList42);
    ArrayList localArrayList43 = new ArrayList(1);
    localArrayList43.add("PK");
    localHashMap.put(Integer.valueOf(92), localArrayList43);
    ArrayList localArrayList44 = new ArrayList(1);
    localArrayList44.add("AF");
    localHashMap.put(Integer.valueOf(93), localArrayList44);
    ArrayList localArrayList45 = new ArrayList(1);
    localArrayList45.add("LK");
    localHashMap.put(Integer.valueOf(94), localArrayList45);
    ArrayList localArrayList46 = new ArrayList(1);
    localArrayList46.add("MM");
    localHashMap.put(Integer.valueOf(95), localArrayList46);
    ArrayList localArrayList47 = new ArrayList(1);
    localArrayList47.add("IR");
    localHashMap.put(Integer.valueOf(98), localArrayList47);
    ArrayList localArrayList48 = new ArrayList(1);
    localArrayList48.add("SS");
    localHashMap.put(Integer.valueOf(211), localArrayList48);
    ArrayList localArrayList49 = new ArrayList(2);
    localArrayList49.add("MA");
    localArrayList49.add("EH");
    localHashMap.put(Integer.valueOf(212), localArrayList49);
    ArrayList localArrayList50 = new ArrayList(1);
    localArrayList50.add("DZ");
    localHashMap.put(Integer.valueOf(213), localArrayList50);
    ArrayList localArrayList51 = new ArrayList(1);
    localArrayList51.add("TN");
    localHashMap.put(Integer.valueOf(216), localArrayList51);
    ArrayList localArrayList52 = new ArrayList(1);
    localArrayList52.add("LY");
    localHashMap.put(Integer.valueOf(218), localArrayList52);
    ArrayList localArrayList53 = new ArrayList(1);
    localArrayList53.add("GM");
    localHashMap.put(Integer.valueOf(220), localArrayList53);
    ArrayList localArrayList54 = new ArrayList(1);
    localArrayList54.add("SN");
    localHashMap.put(Integer.valueOf(221), localArrayList54);
    ArrayList localArrayList55 = new ArrayList(1);
    localArrayList55.add("MR");
    localHashMap.put(Integer.valueOf(222), localArrayList55);
    ArrayList localArrayList56 = new ArrayList(1);
    localArrayList56.add("ML");
    localHashMap.put(Integer.valueOf(223), localArrayList56);
    ArrayList localArrayList57 = new ArrayList(1);
    localArrayList57.add("GN");
    localHashMap.put(Integer.valueOf(224), localArrayList57);
    ArrayList localArrayList58 = new ArrayList(1);
    localArrayList58.add("CI");
    localHashMap.put(Integer.valueOf(225), localArrayList58);
    ArrayList localArrayList59 = new ArrayList(1);
    localArrayList59.add("BF");
    localHashMap.put(Integer.valueOf(226), localArrayList59);
    ArrayList localArrayList60 = new ArrayList(1);
    localArrayList60.add("NE");
    localHashMap.put(Integer.valueOf(227), localArrayList60);
    ArrayList localArrayList61 = new ArrayList(1);
    localArrayList61.add("TG");
    localHashMap.put(Integer.valueOf(228), localArrayList61);
    ArrayList localArrayList62 = new ArrayList(1);
    localArrayList62.add("BJ");
    localHashMap.put(Integer.valueOf(229), localArrayList62);
    ArrayList localArrayList63 = new ArrayList(1);
    localArrayList63.add("MU");
    localHashMap.put(Integer.valueOf(230), localArrayList63);
    ArrayList localArrayList64 = new ArrayList(1);
    localArrayList64.add("LR");
    localHashMap.put(Integer.valueOf(231), localArrayList64);
    ArrayList localArrayList65 = new ArrayList(1);
    localArrayList65.add("SL");
    localHashMap.put(Integer.valueOf(232), localArrayList65);
    ArrayList localArrayList66 = new ArrayList(1);
    localArrayList66.add("GH");
    localHashMap.put(Integer.valueOf(233), localArrayList66);
    ArrayList localArrayList67 = new ArrayList(1);
    localArrayList67.add("NG");
    localHashMap.put(Integer.valueOf(234), localArrayList67);
    ArrayList localArrayList68 = new ArrayList(1);
    localArrayList68.add("TD");
    localHashMap.put(Integer.valueOf(235), localArrayList68);
    ArrayList localArrayList69 = new ArrayList(1);
    localArrayList69.add("CF");
    localHashMap.put(Integer.valueOf(236), localArrayList69);
    ArrayList localArrayList70 = new ArrayList(1);
    localArrayList70.add("CM");
    localHashMap.put(Integer.valueOf(237), localArrayList70);
    ArrayList localArrayList71 = new ArrayList(1);
    localArrayList71.add("CV");
    localHashMap.put(Integer.valueOf(238), localArrayList71);
    ArrayList localArrayList72 = new ArrayList(1);
    localArrayList72.add("ST");
    localHashMap.put(Integer.valueOf(239), localArrayList72);
    ArrayList localArrayList73 = new ArrayList(1);
    localArrayList73.add("GQ");
    localHashMap.put(Integer.valueOf(240), localArrayList73);
    ArrayList localArrayList74 = new ArrayList(1);
    localArrayList74.add("GA");
    localHashMap.put(Integer.valueOf(241), localArrayList74);
    ArrayList localArrayList75 = new ArrayList(1);
    localArrayList75.add("CG");
    localHashMap.put(Integer.valueOf(242), localArrayList75);
    ArrayList localArrayList76 = new ArrayList(1);
    localArrayList76.add("CD");
    localHashMap.put(Integer.valueOf(243), localArrayList76);
    ArrayList localArrayList77 = new ArrayList(1);
    0.add("AO");
    Integer.valueOf(244).put(localArrayList77, 0);
    ArrayList localArrayList78 = new ArrayList(1);
    3.add("GW");
    Integer.valueOf(245).put(localArrayList78, 3);
    ArrayList localArrayList79 = new ArrayList(1);
    0L.add("IO");
    Integer.valueOf(246).put(localArrayList79, 0L);
    ArrayList localArrayList80 = new ArrayList(1);
    1.0F.add("AC");
    Integer.valueOf(247).put(localArrayList80, 1.0F);
    ArrayList localArrayList81 = new ArrayList(1);
    1.0D.add("SC");
    Integer.valueOf(248).put(localArrayList81, 1.0D);
    ArrayList localArrayList82 = new ArrayList(1);
    null.add(0);
    Integer.valueOf(249)[localArrayList82] = "MM";
    0;
    ArrayList localArrayList83 = new ArrayList(1);
    int m;
    null.add(2);
    int i2;
    Integer.valueOf(250)[localArrayList83] = i2;
    0;
    ArrayList localArrayList84 = new ArrayList(1);
    null.add(4);
    Integer.valueOf(251)[localArrayList84] = i2;
    0;
    ArrayList localArrayList85 = new ArrayList(1);
    localArrayList1.add("SO");
    Integer.valueOf(252).put(localArrayList85, localArrayList1);
    ArrayList localArrayList86 = new ArrayList(1);
    localHashMap.add("DJ");
    Integer.valueOf(253).put(localArrayList86, localHashMap);
    ArrayList localArrayList87 = new ArrayList(1);
    Object localObject3;
    localObject3.add("KE");
    Integer.valueOf(254).put(localArrayList87, localObject3);
    ArrayList localArrayList88 = new ArrayList(1);
    Object localObject2;
    localObject2.add("TZ");
    Integer.valueOf(255).put(localArrayList88, localObject2);
    ArrayList localArrayList89 = new ArrayList(1);
    localArrayList1.add("UG");
    Integer.valueOf(256).put(localArrayList89, localArrayList1);
    ArrayList localArrayList90 = new ArrayList(1);
    localHashMap.add("BI");
    Integer.valueOf(257).put(localArrayList90, localHashMap);
    ArrayList localArrayList91 = new ArrayList(1);
    localObject3.add("MZ");
    Integer.valueOf(258).put(localArrayList91, localObject3);
    ArrayList localArrayList92 = new ArrayList(1);
    localArrayList91[localHashMap][localArrayList92].add("ZM");
    localObject3.put(localHashMap, Integer.valueOf(260)[localArrayList92]);
    ArrayList localArrayList93 = new ArrayList(1);
    localArrayList90[localHashMap][localArrayList93].add("MG");
    localHashMap.put(localHashMap, Integer.valueOf(261)[localArrayList93]);
    ArrayList localArrayList94 = new ArrayList(2);
    int i4 = localHashMap;
    int n = localArrayList1;
    null.add(localArrayList1);
    int i1 = localArrayList94;
    null.add(localObject3);
    int i3 = localArrayList94;
    localArrayList89[localHashMap] = Integer.valueOf(262);
    0;
    ArrayList localArrayList95 = new ArrayList(1);
    double d2 = localArrayList1;
    ArrayList localArrayList2 = localArrayList1;
    null.add(localArrayList1);
    Object localObject4 = localArrayList95;
    localHashMap[localHashMap] = Integer.valueOf(263);
    0;
    ArrayList localArrayList96 = new ArrayList(1);
    int i = localArrayList88;
    int j = localArrayList96;
    localObject2.add("NA");
    int k = localArrayList96;
    localHashMap.put(localHashMap, Integer.valueOf(264));
    ArrayList localArrayList97 = new ArrayList(1);
    long l = localArrayList87;
    l = localArrayList97;
    localObject3.add("MW");
    l = localArrayList97;
    localHashMap.put(localHashMap, Integer.valueOf(265));
    ArrayList localArrayList98 = new ArrayList(1);
    float f1 = localArrayList86;
    f1 = localArrayList98;
    localHashMap.add("LS");
    f1 = localArrayList98;
    localHashMap.put(f1, Integer.valueOf(266));
    ArrayList localArrayList99 = new ArrayList(1);
    float f2 = localArrayList85;
    f2 = localArrayList99;
    localArrayList1.add("BW");
    f2 = localArrayList99;
    localHashMap.put(f1, Integer.valueOf(267));
    ArrayList localArrayList100 = new ArrayList(1);
    double d1 = m;
    d1 = localArrayList100;
    localArrayList1.add("SZ");
    d1 = localArrayList100;
    localArrayList56.put(f1, Integer.valueOf(268));
    ArrayList localArrayList101 = new ArrayList(1);
    Object localObject1 = localHashMap;
    localObject1 = localArrayList101;
    m.add("KM");
    localObject1 = localArrayList101;
    localArrayList1.put(f1, Integer.valueOf(269));
    ArrayList localArrayList102 = new ArrayList(2);
    [localHashMap] = localArrayList56;
    [localArrayList1] = localArrayList102;
    localHashMap.add("SH");
    1.0D[localArrayList81] = localArrayList102;
    localHashMap.add("TA");
    f1[Integer.valueOf(290)] = localArrayList102;
    localHashMap.put(1.0F, localArrayList80);
    ArrayList localArrayList103 = new ArrayList(1);
    localHashMap[0L] = localArrayList79;
    3[localArrayList78] = localArrayList103;
    localHashMap.add("ER");
    f1[Integer.valueOf(291)] = localArrayList103;
  }
}

/* Location:           E:\Study\Tools\apktool2_2\dex2jar-0.0.9.15\classes_viber_dex2jar.jar
 * Qualified Name:     c.b.a.a.d
 * JD-Core Version:    0.6.2
 */