package aaa.bbb.ccc;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import aaa.bbb.ccc.tabel_1_note;

import aaa.bbb.ccc.tabel_1_noteDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig tabel_1_noteDaoConfig;

    private final tabel_1_noteDao tabel_1_noteDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        tabel_1_noteDaoConfig = daoConfigMap.get(tabel_1_noteDao.class).clone();
        tabel_1_noteDaoConfig.initIdentityScope(type);

        tabel_1_noteDao = new tabel_1_noteDao(tabel_1_noteDaoConfig, this);

        registerDao(tabel_1_note.class, tabel_1_noteDao);
    }
    
    public void clear() {
        tabel_1_noteDaoConfig.getIdentityScope().clear();
    }

    public tabel_1_noteDao getTabel_1_noteDao() {
        return tabel_1_noteDao;
    }

}
