package aaa.bbb.ccc;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TABEL_1_NOTE".
 */
public class tabel_1_note {

    private Long id;
    /** Not-null value. */
    private String prop_1_text;
    private String prop_2_comment;
    private java.util.Date prop_3_date;

    public tabel_1_note() {
    }

    public tabel_1_note(Long id) {
        this.id = id;
    }

    public tabel_1_note(Long id, String prop_1_text, String prop_2_comment, java.util.Date prop_3_date) {
        this.id = id;
        this.prop_1_text = prop_1_text;
        this.prop_2_comment = prop_2_comment;
        this.prop_3_date = prop_3_date;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getProp_1_text() {
        return prop_1_text;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProp_1_text(String prop_1_text) {
        this.prop_1_text = prop_1_text;
    }

    public String getProp_2_comment() {
        return prop_2_comment;
    }

    public void setProp_2_comment(String prop_2_comment) {
        this.prop_2_comment = prop_2_comment;
    }

    public java.util.Date getProp_3_date() {
        return prop_3_date;
    }

    public void setProp_3_date(java.util.Date prop_3_date) {
        this.prop_3_date = prop_3_date;
    }

}
