package com.viber.voip.h;

import com.viber.service.VoipConnectorService.a;
import com.viber.voip.ViberApplication;
import com.viber.voip.contacts.ui.ParticipantSelector;
import com.viber.voip.invitelinks.n.a;
import com.viber.voip.invitelinks.n.b;
import com.viber.voip.invitelinks.o;
import com.viber.voip.messages.a.c.a;
import com.viber.voip.messages.a.c.b;
import com.viber.voip.messages.a.c.c;
import com.viber.voip.messages.a.c.d;
import com.viber.voip.messages.a.c.e;
import com.viber.voip.messages.a.c.f;
import com.viber.voip.messages.a.c.g;
import com.viber.voip.messages.a.c.h;
import com.viber.voip.messages.a.c.i;
import com.viber.voip.messages.a.d.d;
import com.viber.voip.messages.a.d.e;
import com.viber.voip.messages.a.f.a;
import com.viber.voip.messages.a.f.a.a;
import com.viber.voip.messages.a.f.b;
import com.viber.voip.messages.a.g.a;
import com.viber.voip.messages.a.g.b;
import com.viber.voip.messages.a.h.a;
import com.viber.voip.messages.a.i.a;
import com.viber.voip.messages.a.i.b;
import com.viber.voip.messages.a.j.a;
import com.viber.voip.messages.a.j.b;
import com.viber.voip.messages.a.l.a;
import com.viber.voip.messages.a.l.b;
import com.viber.voip.messages.a.l.c;
import com.viber.voip.messages.controller.b.m.b;
import com.viber.voip.messages.controller.manager.an;
import com.viber.voip.messages.controller.manager.ao;
import com.viber.voip.messages.controller.manager.az;
import com.viber.voip.messages.conversation.ac;
import com.viber.voip.messages.conversation.n;
import com.viber.voip.messages.conversation.ui.SpamController;
import com.viber.voip.messages.conversation.ui.bd;
import com.viber.voip.messages.conversation.ui.presenter.ShareScreenshotPresenter;
import com.viber.voip.messages.conversation.z;
import com.viber.voip.messages.extensions.b.i;
import com.viber.voip.messages.ui.bk;
import com.viber.voip.notif.i.d;
import com.viber.voip.q.h;
import com.viber.voip.q.l;
import com.viber.voip.q.m;
import com.viber.voip.registration.changephonenumber.ChangePhoneNumberActivity;
import com.viber.voip.user.ProfileNotification;
import com.viber.voip.user.UserData.OwnerChangedEvent;
import com.viber.voip.user.UserProfilePreviewActivity.UserProfilePreviewFragment;
import com.viber.voip.user.editinfo.EditInfoPresenter;
import com.viber.voip.user.editinfo.changeemail.ChangeEmailPresenter;
import com.viber.voip.user.editinfo.changepassword.ChangePasswordPresenter;
import com.viber.voip.user.editinfo.diconnectaccount.DisconnectAccountPresenter;
import com.viber.voip.user.editinfo.forgotpassword.ForgotPasswordPresenter;
import com.viber.voip.user.viberid.ViberIdEvents.UnlinkViberIdEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdChangePasswordActionEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdEmailChangingEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdEmailStatusEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdForgotPasswordActionEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdInfoChangedEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdRegistrationEvent;
import com.viber.voip.user.viberid.ViberIdEvents.ViberIdRetypePasswordActionEvent;
import com.viber.voip.user.viberid.ViberIdTriggerStateHolder;
import com.viber.voip.user.viberid.connectaccount.connectsteps.emailstep.RetypePasswordDialogPresenter;
import com.viber.voip.user.viberid.connectaccount.connectsteps.emailstep.ViberIdEmailStepPresenter;
import com.viber.voip.user.viberid.connectaccount.connectsteps.passwordstep.ViberIdPasswordStepPresenter;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import org.greenrobot.eventbus.ThreadMode;
import org.greenrobot.eventbus.meta.SimpleSubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfo;
import org.greenrobot.eventbus.meta.SubscriberInfoIndex;
import org.greenrobot.eventbus.meta.SubscriberMethodInfo;

public class b
  implements SubscriberInfoIndex
{
  private static final Map<Class<?>, SubscriberInfo> a = new HashMap();

  static
  {
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo1 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo1[0] = new SubscriberMethodInfo("onViberIdPasswordActionReceived", ViberIdEvents.ViberIdRetypePasswordActionEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(RetypePasswordDialogPresenter.class, true, arrayOfSubscriberMethodInfo1));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo2 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo2[0] = new SubscriberMethodInfo("onInviteLinkReceived", com.viber.voip.invitelinks.d.c.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.invitelinks.f.class, true, arrayOfSubscriberMethodInfo2));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo3 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo3[0] = new SubscriberMethodInfo("onBroadcastListCreated", com.viber.voip.messages.a.a.a.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo3[1] = new SubscriberMethodInfo("onBanReply", c.a.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo3[2] = new SubscriberMethodInfo("onMembersInvitationLinkReceived", c.f.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ParticipantSelector.class, true, arrayOfSubscriberMethodInfo3));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo4 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo4[0] = new SubscriberMethodInfo("onLastMessageIdReady", c.g.class);
    arrayOfSubscriberMethodInfo4[1] = new SubscriberMethodInfo("onCancelReferralJoinEvent", c.b.class);
    a(new SimpleSubscriberInfo(com.viber.voip.invitelinks.j.class, true, arrayOfSubscriberMethodInfo4));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo5 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo5[0] = new SubscriberMethodInfo("onLocationAddressSet", h.a.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(d.class, true, arrayOfSubscriberMethodInfo5));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo6 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo6[0] = new SubscriberMethodInfo("onClearPrefsEvent", com.viber.voip.settings.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.i.j.class, true, arrayOfSubscriberMethodInfo6));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo7 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo7[0] = new SubscriberMethodInfo("onEvent", VoipConnectorService.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.fcm.f.class, true, arrayOfSubscriberMethodInfo7));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo8 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo8[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(UserProfilePreviewActivity.UserProfilePreviewFragment.class, true, arrayOfSubscriberMethodInfo8));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo9 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo9[0] = new SubscriberMethodInfo("onSentMessageReceived", c.i.class);
    a(new SimpleSubscriberInfo(com.viber.voip.messages.controller.b.x.class, true, arrayOfSubscriberMethodInfo9));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo10 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo10[0] = new SubscriberMethodInfo("onInviteLinkReceived", com.viber.voip.invitelinks.d.c.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo10[1] = new SubscriberMethodInfo("onDisplayInvitationLinkChanged", com.viber.voip.invitelinks.d.a.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.invitelinks.linkscreen.j.class, true, arrayOfSubscriberMethodInfo10));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo11 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo11[0] = new SubscriberMethodInfo("onCheckGdprEvent", com.viber.voip.ui.e.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.gdpr.c.class, true, arrayOfSubscriberMethodInfo11));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo12 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo12[0] = new SubscriberMethodInfo("onPasswordActionReply", ViberIdEvents.ViberIdChangePasswordActionEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo12[1] = new SubscriberMethodInfo("onViberIdInfoChanged", ViberIdEvents.ViberIdInfoChangedEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ChangePasswordPresenter.class, true, arrayOfSubscriberMethodInfo12));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo13 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo13[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class);
    a(new SimpleSubscriberInfo(z.class, true, arrayOfSubscriberMethodInfo13));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo14 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo14[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class);
    a(new SimpleSubscriberInfo(ac.class, true, arrayOfSubscriberMethodInfo14));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo15 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo15[0] = new SubscriberMethodInfo("onViberIdRegistrationResult", ViberIdEvents.ViberIdRegistrationEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ViberIdPasswordStepPresenter.class, true, arrayOfSubscriberMethodInfo15));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo16 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo16[0] = new SubscriberMethodInfo("onAcceptGroupInvite", n.a.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.api.scheme.action.b.class, true, arrayOfSubscriberMethodInfo16));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo17 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo17[0] = new SubscriberMethodInfo("onLanguageChanged", g.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.vln.g.class, true, arrayOfSubscriberMethodInfo17));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo18 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo18[0] = new SubscriberMethodInfo("onViberIdEmailStatusReceived", ViberIdEvents.ViberIdEmailStatusEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ViberIdEmailStepPresenter.class, true, arrayOfSubscriberMethodInfo18));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo19 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo19[0] = new SubscriberMethodInfo("onEvent", com.viber.voip.fcm.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.analytics.a.b.class, true, arrayOfSubscriberMethodInfo19));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo20 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo20[0] = new SubscriberMethodInfo("onConversationUpdateEvent", d.d.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(com.viber.voip.analytics.b.c.class, true, arrayOfSubscriberMethodInfo20));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo21 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo21[0] = new SubscriberMethodInfo("onEvent", f.b.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(bd.class, true, arrayOfSubscriberMethodInfo21));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo22 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo22[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class);
    a(new SimpleSubscriberInfo(com.viber.voip.messages.conversation.x.class, true, arrayOfSubscriberMethodInfo22));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo23 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo23[0] = new SubscriberMethodInfo("onCheckAllowsM2MChatEventReceived", c.c.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.contacts.ui.list.u.class, true, arrayOfSubscriberMethodInfo23));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo24 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo24[0] = new SubscriberMethodInfo("onViberIdInfoChanged", ViberIdEvents.ViberIdInfoChangedEvent.class);
    a(new SimpleSubscriberInfo(ViberIdTriggerStateHolder.class, true, arrayOfSubscriberMethodInfo24));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo25 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo25[0] = new SubscriberMethodInfo("onUnlinkViberIdReply", ViberIdEvents.UnlinkViberIdEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(DisconnectAccountPresenter.class, true, arrayOfSubscriberMethodInfo25));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo26 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo26[0] = new SubscriberMethodInfo("onEvent", f.a.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(f.a.a.class, true, arrayOfSubscriberMethodInfo26));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo27 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo27[0] = new SubscriberMethodInfo("onEvent", com.viber.voip.app.b.a.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ViberApplication.class, true, arrayOfSubscriberMethodInfo27));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo28 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo28[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class);
    a(new SimpleSubscriberInfo(n.class, true, arrayOfSubscriberMethodInfo28));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo29 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo29[0] = new SubscriberMethodInfo("onGroupInfoRequestedForAddedByLinkGroup", m.b.class);
    a(new SimpleSubscriberInfo(o.class, true, arrayOfSubscriberMethodInfo29));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo30 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo30[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class);
    a(new SimpleSubscriberInfo(ProfileNotification.class, true, arrayOfSubscriberMethodInfo30));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo31 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo31[0] = new SubscriberMethodInfo("onStickerClickerReceived", com.viber.voip.banner.c.a.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.banner.b.a.class, true, arrayOfSubscriberMethodInfo31));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo32 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo32[0] = new SubscriberMethodInfo("reschedule", com.viber.voip.messages.a.d.b.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(ao.class, true, arrayOfSubscriberMethodInfo32));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo33 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo33[0] = new SubscriberMethodInfo("onClosePanelRequested", com.viber.voip.messages.a.b.a.class);
    a(new SimpleSubscriberInfo(i.class, true, arrayOfSubscriberMethodInfo33));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo34 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo34[0] = new SubscriberMethodInfo("onUserIsTyping", d.e.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo34[1] = new SubscriberMethodInfo("onGroupUserIsTyping", com.viber.voip.messages.a.d.c.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(bk.class, true, arrayOfSubscriberMethodInfo34));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo35 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo35[0] = new SubscriberMethodInfo("onAuthorizedEvent", com.viber.voip.registration.changephonenumber.a.b.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo35[1] = new SubscriberMethodInfo("onActivatedEvent", com.viber.voip.registration.changephonenumber.a.a.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ChangePhoneNumberActivity.class, true, arrayOfSubscriberMethodInfo35));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo36 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo36[0] = new SubscriberMethodInfo("onRefreshData", com.viber.voip.messages.a.k.class);
    arrayOfSubscriberMethodInfo36[1] = new SubscriberMethodInfo("onGetInvitationMemberMessage", c.e.class);
    arrayOfSubscriberMethodInfo36[2] = new SubscriberMethodInfo("onMiddleStateCommunityCreated", c.h.class);
    a(new SimpleSubscriberInfo(com.viber.voip.messages.controller.a.class, true, arrayOfSubscriberMethodInfo36));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo37 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo37[0] = new SubscriberMethodInfo("onEmailChangedReply", ViberIdEvents.ViberIdEmailChangingEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo37[1] = new SubscriberMethodInfo("onViberIdInfoChanged", ViberIdEvents.ViberIdInfoChangedEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ChangeEmailPresenter.class, true, arrayOfSubscriberMethodInfo37));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo38 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo38[0] = new SubscriberMethodInfo("onMessageEdited", j.a.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(com.viber.voip.notif.i.c.class, true, arrayOfSubscriberMethodInfo38));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo39 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo39[0] = new SubscriberMethodInfo("onPasswordActionReply", ViberIdEvents.ViberIdForgotPasswordActionEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(ForgotPasswordPresenter.class, true, arrayOfSubscriberMethodInfo39));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo40 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo40[0] = new SubscriberMethodInfo("onLocalUnpin", j.b.class);
    a(new SimpleSubscriberInfo(com.viber.voip.messages.conversation.adapter.a.b.f.class, true, arrayOfSubscriberMethodInfo40));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo41 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo41[0] = new SubscriberMethodInfo("onEvent", VoipConnectorService.a.class);
    a(new SimpleSubscriberInfo(com.viber.voip.notif.e.u.class, true, arrayOfSubscriberMethodInfo41));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo42 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo42[0] = new SubscriberMethodInfo("onLanguageSelectedInSettings", g.b.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.l.a.class, true, arrayOfSubscriberMethodInfo42));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo43 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo43[0] = new SubscriberMethodInfo("onEvent", i.b.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(i.a.class, true, arrayOfSubscriberMethodInfo43));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo44 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo44[0] = new SubscriberMethodInfo("onActivationSmsReceived", com.viber.voip.registration.sms.a.class, ThreadMode.MAIN, 0, true);
    a(new SimpleSubscriberInfo(com.viber.voip.registration.e.class, true, arrayOfSubscriberMethodInfo44));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo45 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo45[0] = new SubscriberMethodInfo("onGroupLinkReceived", n.b.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.invitelinks.linkscreen.k.class, true, arrayOfSubscriberMethodInfo45));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo46 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo46[0] = new SubscriberMethodInfo("onRecordStateChanged", com.viber.voip.u.b.class, ThreadMode.MAIN_ORDERED);
    a(new SimpleSubscriberInfo(com.viber.voip.u.c.class, true, arrayOfSubscriberMethodInfo46));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo47 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo47[0] = new SubscriberMethodInfo("onUserIsTyping", d.e.class);
    arrayOfSubscriberMethodInfo47[1] = new SubscriberMethodInfo("onGroupUserIsTyping", com.viber.voip.messages.a.d.c.class);
    a(new SimpleSubscriberInfo(com.viber.voip.messages.conversation.ui.j.class, true, arrayOfSubscriberMethodInfo47));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo48 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo48[0] = new SubscriberMethodInfo("onOwnerChanged", UserData.OwnerChangedEvent.class, ThreadMode.MAIN);
    arrayOfSubscriberMethodInfo48[1] = new SubscriberMethodInfo("onViberIdInfoChanged", ViberIdEvents.ViberIdInfoChangedEvent.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(EditInfoPresenter.class, true, arrayOfSubscriberMethodInfo48));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo49 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo49[0] = new SubscriberMethodInfo("onHomeTabChanged", com.viber.voip.ui.e.c.class, ThreadMode.POSTING, 0, true);
    arrayOfSubscriberMethodInfo49[1] = new SubscriberMethodInfo("onConversationsLoaded", com.viber.voip.ui.e.b.class, ThreadMode.POSTING, 0, true);
    a(new SimpleSubscriberInfo(com.viber.voip.engagement.a.class, true, arrayOfSubscriberMethodInfo49));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo50 = new SubscriberMethodInfo[4];
    arrayOfSubscriberMethodInfo50[0] = new SubscriberMethodInfo("sendChangeMessage", com.viber.voip.messages.a.d.b.class, ThreadMode.BACKGROUND);
    arrayOfSubscriberMethodInfo50[1] = new SubscriberMethodInfo("sendChangeMessage", Set.class, ThreadMode.BACKGROUND);
    arrayOfSubscriberMethodInfo50[2] = new SubscriberMethodInfo("sendRequestMessage", com.viber.voip.messages.a.d.a.class, ThreadMode.BACKGROUND);
    arrayOfSubscriberMethodInfo50[3] = new SubscriberMethodInfo("sendRequestMessage", com.viber.voip.messages.a.k.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(az.class, true, arrayOfSubscriberMethodInfo50));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo51 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo51[0] = new SubscriberMethodInfo("onAcceptGroupInvite", com.viber.voip.invitelinks.d.b.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(com.viber.voip.api.scheme.action.a.class, true, arrayOfSubscriberMethodInfo51));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo52 = new SubscriberMethodInfo[3];
    arrayOfSubscriberMethodInfo52[0] = new SubscriberMethodInfo("onConversationTimeBombChanged", l.c.class, ThreadMode.BACKGROUND);
    arrayOfSubscriberMethodInfo52[1] = new SubscriberMethodInfo("onConversationScreenShotTaken", l.b.class, ThreadMode.BACKGROUND);
    arrayOfSubscriberMethodInfo52[2] = new SubscriberMethodInfo("onConversation1to1Started", l.a.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(an.class, true, arrayOfSubscriberMethodInfo52));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo53 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo53[0] = new SubscriberMethodInfo("onRecordStateChanged", l.class, ThreadMode.MAIN_ORDERED);
    a(new SimpleSubscriberInfo(m.class, true, arrayOfSubscriberMethodInfo53));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo54 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo54[0] = new SubscriberMethodInfo("onInviteLinkReceived", com.viber.voip.invitelinks.d.c.class, ThreadMode.BACKGROUND);
    a(new SimpleSubscriberInfo(ShareScreenshotPresenter.class, true, arrayOfSubscriberMethodInfo54));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo55 = new SubscriberMethodInfo[1];
    arrayOfSubscriberMethodInfo55[0] = new SubscriberMethodInfo("onCommonCommunitiesReceived", c.d.class, ThreadMode.MAIN);
    a(new SimpleSubscriberInfo(SpamController.class, true, arrayOfSubscriberMethodInfo55));
    SubscriberMethodInfo[] arrayOfSubscriberMethodInfo56 = new SubscriberMethodInfo[2];
    arrayOfSubscriberMethodInfo56[0] = new SubscriberMethodInfo("onPlayerStateChanged", com.viber.voip.q.g.class, ThreadMode.MAIN_ORDERED);
    arrayOfSubscriberMethodInfo56[1] = new SubscriberMethodInfo("onProgressChanged", com.viber.voip.q.e.class, ThreadMode.MAIN_ORDERED);
    a(new SimpleSubscriberInfo(h.class, true, arrayOfSubscriberMethodInfo56));
  }

  private static void a(SubscriberInfo paramSubscriberInfo)
  {
    a.put(paramSubscriberInfo.getSubscriberClass(), paramSubscriberInfo);
  }

  public SubscriberInfo getSubscriberInfo(Class<?> paramClass)
  {
    SubscriberInfo localSubscriberInfo = (SubscriberInfo)a.get(paramClass);
    if (localSubscriberInfo != null)
      return localSubscriberInfo;
    return null;
  }
}

/* Location:           E:\Study\Tools\apktool2_2\dex2jar-0.0.9.15\classes_viber_3_dex2jar.jar
 * Qualified Name:     com.viber.voip.h.b
 * JD-Core Version:    0.6.2
 */